Document: libnice
Title: Debian libnice Manual
Author: <insert document author here>
Abstract: This manual describes what libnice is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libnice/libnice.sgml.gz

Format: postscript
Files: /usr/share/doc/libnice/libnice.ps.gz

Format: text
Files: /usr/share/doc/libnice/libnice.text.gz

Format: HTML
Index: /usr/share/doc/libnice/html/index.html
Files: /usr/share/doc/libnice/html/*.html
